common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns=[
    path('main/', views.main, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name = "common/login.html"), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('show/', views.profile_view, name='show'),
    path('show/update/', views.profile_update_view, name='profile_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dorms/', include('dorms.urls')),
    path('common/', include('common.urls')),
    path('washing_machine/', include('washing_machine.urls')),
    re_path(r'^webpush/', include('webpush.urls')),
    path('conversations/',include('conversations.urls')),
]

dorms/urls.py
from django.urls import path
from . import views

app_name = 'dorms'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('<int:context_id>/', views.detail, name='detail'),
    path ('comment/create/<int:context_id>/', views.comment_create, name='comment_create'),
    path ('context/create/', views.context_create, name = 'context_create'),
    path ('context/modify/<int:context_id>/', views.context_modify, name='context_modify'),
    path ('context/delete/<int:context_id>/', views.context_delete, name='context_delete'),
    path ('context/comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path ('context/comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path ('info/', views.info_index, name='info_index'),
    path ('info/<int:context_id>/', views.info_detail, name='info_detail'),
    path ('info/comment/create/<int:context_id>/', views.info_comment_create, name='info_comment_create'),
    path ('info/context/create/', views.info_context_create, name = 'info_context_create'),
    path ('info/context/modify/<int:context_id>/', views.info_context_modify, name='info_context_modify'),
    path ('info/context/delete/<int:context_id>/', views.info_context_delete, name='info_context_delete'),
    path ('info/context/comment/modify/<int:comment_id>/', views.info_comment_modify, name='info_comment_modify'),
    path ('info/context/comment/delete/<int:comment_id>/', views.info_comment_delete, name='info_comment_delete'),
    path ('free/', views.free_index, name='free_index'),
    path ('free/<int:context_id>/', views.free_detail, name='free_detail'),
    path ('free/comment/create/<int:context_id>/', views.free_comment_create, name='free_comment_create'),
    path ('free/context/create/', views.free_context_create, name = 'free_context_create'),
    path ('free/context/modify/<int:context_id>/', views.free_context_modify, name='free_context_modify'),
    path ('free/context/delete/<int:context_id>/', views.free_context_delete, name='free_context_delete'),
    path ('free/context/comment/modify/<int:comment_id>/', views.free_comment_modify, name='free_comment_modify'),
    path ('free/context/comment/delete/<int:comment_id>/', views.free_comment_delete, name='free_comment_delete'),
    path ('trade/', views.trade_index, name='trade_index'),
    path ('trade/<int:context_id>/', views.trade_detail, name='trade_detail'),
    path ('trade/comment/create/<int:context_id>/', views.trade_comment_create, name='trade_comment_create'),
    path ('trade/context/create/', views.trade_context_create, name = 'trade_context_create'),
    path ('trade/context/modify/<int:context_id>/', views.trade_context_modify, name='trade_context_modify'),
    path ('trade/context/delete/<int:context_id>/', views.trade_context_delete, name='trade_context_delete'),
    path ('trade/context/comment/modify/<int:comment_id>/', views.trade_comment_modify, name='trade_comment_modify'),
    path ('trade/context/comment/delete/<int:comment_id>/', views.trade_comment_delete, name='trade_comment_delete'),
    path ('copurchase/', views.copurchase_index, name='copurchase_index'),
    path ('copurchase/<int:context_id>/', views.copurchase_detail, name='copurchase_detail'),
    path ('copurchase/comment/create/<int:context_id>/', views.copurchase_comment_create, name='copurchase_comment_create'),
    path ('copurchase/context/create/', views.copurchase_context_create, name = 'copurchase_context_create'),
    path ('copurchase/context/modify/<int:context_id>/', views.copurchase_context_modify, name='copurchase_context_modify'),
    path ('copurchase/context/delete/<int:context_id>/', views.copurchase_context_delete, name='copurchase_context_delete'),
    path ('copurchase/context/comment/modify/<int:comment_id>/', views.copurchase_comment_modify, name='copurchase_comment_modify'),
    path ('copurchase/context/comment/delete/<int:comment_id>/', views.copurchase_comment_delete, name='copurchase_comment_delete'),
]

my_dorms/dorms/urls.py
from django.urls import path
from . import views

app_name = 'dorms'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('<int:context_id>/', views.detail, name='detail'),
    path ('comment/create/<int:context_id>/', views.comment_create, name='comment_create'),
    path ('context/create/', views.context_create, name = 'context_create'),
    path ('context/modify/<int:context_id>/', views.context_modify, name='context_modify'),
    path ('context/delete/<int:context_id>/', views.context_delete, name='context_delete'),
    path ('context/comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path ('context/comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path ('info/', views.info_index, name='info_index'),
    path ('info/<int:context_id>/', views.info_detail, name='info_detail'),
    path ('info/comment/create/<int:context_id>/', views.info_comment_create, name='info_comment_create'),
    path ('info/context/create/', views.info_context_create, name = 'info_context_create'),
    path ('info/context/modify/<int:context_id>/', views.info_context_modify, name='info_context_modify'),
    path ('info/context/delete/<int:context_id>/', views.info_context_delete, name='info_context_delete'),
    path ('info/context/comment/modify/<int:comment_id>/', views.info_comment_modify, name='info_comment_modify'),
    path ('info/context/comment/delete/<int:comment_id>/', views.info_comment_delete, name='info_comment_delete'),
    path ('free/', views.free_index, name='free_index'),
    path ('free/<int:context_id>/', views.free_detail, name='free_detail'),
    path ('free/comment/create/<int:context_id>/', views.free_comment_create, name='free_comment_create'),
    path ('free/context/create/', views.free_context_create, name = 'free_context_create'),
    path ('free/context/modify/<int:context_id>/', views.free_context_modify, name='free_context_modify'),
    path ('free/context/delete/<int:context_id>/', views.free_context_delete, name='free_context_delete'),
    path ('free/context/comment/modify/<int:comment_id>/', views.free_comment_modify, name='free_comment_modify'),
    path ('free/context/comment/delete/<int:comment_id>/', views.free_comment_delete, name='free_comment_delete'),
    path ('trade/', views.trade_index, name='trade_index'),
    path ('trade/<int:context_id>/', views.trade_detail, name='trade_detail'),
    path ('trade/comment/create/<int:context_id>/', views.trade_comment_create, name='trade_comment_create'),
    path ('trade/context/create/', views.trade_context_create, name = 'trade_context_create'),
    path ('trade/context/modify/<int:context_id>/', views.trade_context_modify, name='trade_context_modify'),
    path ('trade/context/delete/<int:context_id>/', views.trade_context_delete, name='trade_context_delete'),
    path ('trade/context/comment/modify/<int:comment_id>/', views.trade_comment_modify, name='trade_comment_modify'),
    path ('trade/context/comment/delete/<int:comment_id>/', views.trade_comment_delete, name='trade_comment_delete'),
    path ('copurchase/', views.copurchase_index, name='copurchase_index'),
    path ('copurchase/<int:context_id>/', views.copurchase_detail, name='copurchase_detail'),
    path ('copurchase/comment/create/<int:context_id>/', views.copurchase_comment_create, name='copurchase_comment_create'),
    path ('copurchase/context/create/', views.copurchase_context_create, name = 'copurchase_context_create'),
    path ('copurchase/context/modify/<int:context_id>/', views.copurchase_context_modify, name='copurchase_context_modify'),
    path ('copurchase/context/delete/<int:context_id>/', views.copurchase_context_delete, name='copurchase_context_delete'),
    path ('copurchase/context/comment/modify/<int:comment_id>/', views.copurchase_comment_modify, name='copurchase_comment_modify'),
    path ('copurchase/context/comment/delete/<int:comment_id>/', views.copurchase_comment_delete, name='copurchase_comment_delete'),
    path ('dormmate/', views.dormmate_index, name='dormmate_index'),
    path ('dormmate/<int:context_id>/', views.dormmate_detail, name='dormmate_detail'),
    path ('dormmate/comment/create/<int:context_id>/', views.dormmate_comment_create, name='dormmate_comment_create'),
    path ('dormmate/context/create/', views.dormmate_context_create, name = 'dormmate_context_create'),
    path ('dormmate/context/modify/<int:context_id>/', views.dormmate_context_modify, name='dormmate_context_modify'),
    path ('dormmate/context/delete/<int:context_id>/', views.dormmate_context_delete, name='dormmate_context_delete'),
    path ('dormmate/context/comment/modify/<int:comment_id>/', views.dormmate_comment_modify, name='dormmate_comment_modify'),
    path ('dormmate/context/comment/delete/<int:comment_id>/', views.dormmate_comment_delete, name='dormmate_comment_delete'),
]

my_dorms/washing_machine/urls.py
from django.urls import path
from . import views

app_name = 'washing_machine'

urlpatterns = [
    path('', views.status, name='status'),
    path('camera/', views.camera, name='camera'),
    path('reserve_camera/', views.reserve_camera, name='reserve_camera'),
    path('add/', views.add, name='add'),
    path('reserve/', views.reserve, name='reserve'),
]

washing_machine/urls.py
from django.urls import path
from . import views

app_name = 'washing_machine'

urlpatterns = [
    path('', views.status, name='status'),
    path('camera/', views.camera, name='camera'),
    path('add/', views.add, name='add'),
]

my_dorms/dorms/forms.py
from django import forms
from dorms.models import Context, Comment, Context_info, Comment_info, Context_free, Comment_free, Context_trade, Comment_trade, Comment_copur, Context_copur, Context_dormmate, Comment_dormmate

class ContextForm (forms.ModelForm) :
    class Meta :
        model = Context
        fields = ['title', 'content']

class CommentForm(forms.ModelForm) :
    class Meta :
        model = Comment
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextInfoForm (forms.ModelForm) :
    class Meta :
        model = Context_info
        fields = ['title', 'content']

class CommentInfoForm(forms.ModelForm) :
    class Meta :
        model = Comment_info
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextFreeForm (forms.ModelForm) :
    class Meta :
        model = Context_free
        fields = ['title', 'content']

class CommentFreeForm(forms.ModelForm) :
    class Meta :
        model = Comment_free
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextTradeForm (forms.ModelForm) :
    class Meta :
        model = Context_trade
        fields = ['title', 'content']

class CommentTradeForm(forms.ModelForm) :
    class Meta :
        model = Comment_trade
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextDormmateForm (forms.ModelForm) :
    class Meta :
        model = Context_dormmate
        fields = ['title', 'content', 'isSnoring', 'time_awake_1', 'time_awake_2','time_sleep_1', 'time_sleep_2', 'isSmoking', 'age', 'usingPC','building']    

class CommentDormmateForm(forms.ModelForm) :
    class Meta :
        model = Comment_dormmate
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }
class ContextCopurForm (forms.ModelForm) :
    class Meta :
        model = Context_copur
        fields = ['title', 'content']

class CommentCopurForm(forms.ModelForm) :
    class Meta :
        model = Comment_copur
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

my_dorms/common/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import UserForm, CustomUserChangeForm
from .models import User
from dorms.models import Context
from conversations.services.chat_room_service import get_an_chat_room_list, get_chat_room_user, confirm_user_chat_room_join, \
    creat_an_chat_room, creat_an_room_join

# Create your views here.
def main (request) :
    context_list = Context.objects.all()[:5]
    context = {
        'context_list' : context_list
    }
    return render (request, 'common/main.html', context)

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            #이웃한 방 유저 체크하고 메시지 room 생성
            try: 
                neighbor1 = User.objects.get(building=user.building, room_num=user.room_num+1)
                room = creat_an_chat_room()
                room_id = room.id
                creat_an_room_join(user, neighbor1, room)
                
            except User.DoesNotExist:
                neighbor1 = None
            try: 
                neighbor2 = User.objects.get(building=user.building, room_num=user.room_num-1)
                room = creat_an_chat_room()
                room_id = room.id
                creat_an_room_join(user, neighbor2, room)
            except User.DoesNotExist:
                neighbor2 = None

            



            login(request, user)  # 로그인
            return redirect('common:main')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

def profile_view (request) :
    if request.method == 'GET' :
        return render (request, 'common/profile.html')

def profile_update_view(request) :
    if request.method == 'POST' :
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)

        if user_change_form.is_valid() :
            user = user_change_form.save()
            user.save()
            return render (request, 'common/profile.html')

    else :
        user_change_form = CustomUserChangeForm(instance=request.user)

    return render (request, 'common/profile_update.html', {'user_change_form':user_change_form})

my_dorms/conversations/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse

from django.shortcuts import redirect, reverse, render
from conversations.services.chat_room_service import get_an_chat_room_list, get_chat_room_user, confirm_user_chat_room_join
from conversations.services.message_service import get_an_message_list



#로그인 안할시 로그인 페이지로 이동
@login_required(login_url='common:login')
def chat_view(request: HttpRequest) -> HttpResponse:
    # 사용자의 존재 여부 확인
    user = request.user.is_authenticated
    # 사용자가 있으면 사용자가 속해있는 채팅방 list 표시
    if user:
        # 유저가 참여하고 있는 채팅방 목록(Conversations query)
        chat_room_list = get_an_chat_room_list(request.user.id)
        chat_info = {}
        for chat_room in chat_room_list:
            room_id = chat_room.room_id.id
            # 채팅방에 참여중인 유저 list(Conversations query)
            chat_user_list = get_chat_room_user(room_id)

            username_list = []
            building_info = ''
            roomNum_info = ''
            for chat_user in chat_user_list:
                username = chat_user.user_id.username
                building_info = chat_user.user_id.building
                roomNum_info = chat_user.user_id.room_num
                username_list.append(username)
            # chat_info 변수에 딕셔너리 형태로 저장
            # building_info 및 roomNumber 를 더해 리스트 구성
            username_list.append(building_info)
            username_list.append(roomNum_info)
            chat_info[room_id] = username_list

        if chat_info == {}:
            chat_info = None

        return render(request, "conversations/chat.html", {'chat_info': chat_info})
    # 사용자가 없는 경우 로그인화면
    else:
        return redirect(("/common/login"))

@login_required(login_url='common:login')
def room_view(request: HttpRequest, room_name: str) -> HttpResponse:
    room_id = int(room_name)
    try:
        confirm_user_chat_room_join(request.user.id, room_id)
        
        message = get_an_message_list(room_id)

        return render(request, "conversations/room.html", {"room_name": room_name, "message": message, "user_name": request.user.username})

    except:
        return redirect(("/conversations"))

my_dorms/core/views.py
from django.shortcuts import render

# Create your views here.

my_dorms/templates/washing_machine/status.html
{% extends "dorms/base.html" %}
{% block content %}
{% load static %}
{% load webpush_notifications %}

<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

<nav style="background-color: #1c6758;"class="navbar border-bottom">
  <div id="d-nav" class="container-fluid">
      <ul class="navbar-nav">
          <li class="nav-item">
              <div style="color: white" class="nav-link" onClick="location.href=wm_main_url">뒤로가기</div>
          </li>
      </ul>
      <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
      <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                      <li class="nav-item">
                          <a style="color: white" class="nav-link" href="{% url 'common:show' %}">프로필</a></li>
                  {% else %}
                      <li class="nav-item">
                          <a style="color: white" class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                  {% endif %}
      </ul>
  </div>
</nav>

<div class="wm-container-webpush">
  {% webpush_button with_class="wm-webpush-button"%}
</div>

{% if status_lst %}
  <div class="wm-container-dorminfo">
    <span id="wm-dorminfo">{{ building }}</span>
  </div>
  <div class="wm-container-washingmachine" id="wm-container-machine">
    {% for status in status_lst %}
      <div class="wm-container-washingmachine-element">
        <button type="button" class="wm-button-washingmachine">
          <span class="wm-name-washingmachine">{{status.machine_id}}</span>
          <div class="wm-circular-progress-time"></div>
          <img src="{%static './assets/washingmachine.png' %}" alt="washingmachine">
          <span class="wm-time-washingmachine">{{ status.end_time }}</span>
          <span hidden class="wm-starttime-washingmachine">{{ status.start_time }}</span>
        </button>
        <button type="button" class="wm-button-washingmachine-reservation" onclick="ReservationButtonClicked()"><img src="{%static './assets/button_reservation.png' %}" alt="button_reservation"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}


<div class="wm-container-button-use">
  <button type="button" id="wm-button-use" onclick="UseButtonClicked()"><img src="{%static './assets/button_use.png' %}" alt="button_use"></button>
</div>

{% for message in messages %}
  <div class="wm-container-error-message">
    <span class="wm-error-message">{{ message }}</span>
  </div>
{% endfor %}

<script>
  var wm_machineImage_url = "{%static './assets/washingmachine.png' %}";
  var wm_buttonReservationImage_url = "{%static './assets/button_reservation.png' %}";
  var wm_buttonUseImage_url = "{%static './assets/button_use.png' %}";
  var wm_cameraPage_url = "{% url 'washing_machine:camera' %}";
  var wm_reserve_cameraPage_url = "{% url 'washing_machine:reserve_camera' %}";
  var wm_main_url = "{% url 'common:main' %}";
</script>

<script src="{%static './js/washingMachineState.js' %}"></script>
{% endblock %}

my_dorms/templates/washing_machine/test_camera.html
{% extends "dorms/base.html" %}
{% block content %}
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{%static './js/jsQR.js' %}"></script>

<div class="wm-container-description">
  <span class="wm-description" id="wm-description-qr">QR코드를<br>틀 안에 맞춰주세요.</span>
</div>
<div id="wm-loadingMessage">🎥 Unable to access video stream (please make sure you have a webcam enabled)</div>
<canvas id="wm-canvas" hidden></canvas>
<div id="wm-output" hidden>
  <div id="wm-outputMessage">No QR code detected.</div>
  <div hidden><b>Data:</b> <span id="wm-outputData"></span></div>
</div>

<form method="post" action="{% url 'washing_machine:add' %}" id="wm-camera-info">
  {% csrf_token%}
  <input type="hidden" name="ocr-image" id="wm-ocr-image" value="">
  <input type="hidden" name="ocr-position" id="wm-ocr-position" value="">
  <input type="hidden" name="code-data" id="wm-code-data" value=""> 
</form>

<canvas id="wm-test-canvas" hidden></canvas>
<img src="{%static './assets/washingmachine_test_image.jpg' %}" alt="test" id="wm-test-image" hidden>

<script>
    var wm_test_image_url = "{%static './assets/washingmachine_test_image.jpg' %}";
</script>

<!-- loading -->
<div class="wm-container-loader">
  <div class="wm-loader" id="wm-loader" hidden></div>
</div>

<script src="{%static './js/testCamScript.js' %}"></script>
{% endblock %}

my_dorms/templates/washing_machine/test_reserve.html
{% extends "dorms/base.html" %}
{% block content %}
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{%static './js/jsQR.js' %}"></script>

<div class="wm-container-description">
  <span class="wm-description" id="wm-description-qr">QR코드를<br>틀 안에 맞춰주세요.</span>
</div>
<div id="wm-loadingMessage">🎥 Unable to access video stream (please make sure you have a webcam enabled)</div>
<canvas id="wm-canvas" hidden></canvas>
<div id="wm-output" hidden>
  <div id="wm-outputMessage">No QR code detected.</div>
  <div hidden><b>Data:</b> <span id="wm-outputData"></span></div>
</div>

<form method="post" action="{% url 'washing_machine:reserve' %}" id="wm-camera-info">
  {% csrf_token%}
  <input type="hidden" name="ocr-image" id="wm-ocr-image" value="">
  <input type="hidden" name="ocr-position" id="wm-ocr-position" value="">
  <input type="hidden" name="code-data" id="wm-code-data" value=""> 
</form>

<canvas id="wm-test-canvas" hidden></canvas>
<img src="{%static './assets/washingmachine_test_image.jpeg' %}" alt="test" id="wm-test-image" hidden>

<script>
    var wm_test_image_url = "{%static './assets/washingmachine_test_image.jpeg' %}";
</script>

<!-- loading -->
<div class="wm-container-loader">
  <div class="wm-loader" id="wm-loader" hidden></div>
</div>

<script src="{%static './js/testCamScript.js' %}"></script>
{% endblock %}