common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns=[
    path('main/', views.main, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name = "common/login.html"), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('show/', views.profile_view, name='show'),
    path('show/update/', views.profile_update_view, name='profile_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dorms/', include('dorms.urls')),
    path('common/', include('common.urls')),
    path('washing_machine/', include('washing_machine.urls')),
    re_path(r'^webpush/', include('webpush.urls')),
    path('conversations/',include('conversations.urls')),
]

dorms/urls.py
from django.urls import path
from . import views

app_name = 'dorms'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('<int:context_id>/', views.detail, name='detail'),
    path ('comment/create/<int:context_id>/', views.comment_create, name='comment_create'),
    path ('context/create/', views.context_create, name = 'context_create'),
    path ('context/modify/<int:context_id>/', views.context_modify, name='context_modify'),
    path ('context/delete/<int:context_id>/', views.context_delete, name='context_delete'),
    path ('context/comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path ('context/comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path ('info/', views.info_index, name='info_index'),
    path ('info/<int:context_id>/', views.info_detail, name='info_detail'),
    path ('info/comment/create/<int:context_id>/', views.info_comment_create, name='info_comment_create'),
    path ('info/context/create/', views.info_context_create, name = 'info_context_create'),
    path ('info/context/modify/<int:context_id>/', views.info_context_modify, name='info_context_modify'),
    path ('info/context/delete/<int:context_id>/', views.info_context_delete, name='info_context_delete'),
    path ('info/context/comment/modify/<int:comment_id>/', views.info_comment_modify, name='info_comment_modify'),
    path ('info/context/comment/delete/<int:comment_id>/', views.info_comment_delete, name='info_comment_delete'),
    path ('free/', views.free_index, name='free_index'),
    path ('free/<int:context_id>/', views.free_detail, name='free_detail'),
    path ('free/comment/create/<int:context_id>/', views.free_comment_create, name='free_comment_create'),
    path ('free/context/create/', views.free_context_create, name = 'free_context_create'),
    path ('free/context/modify/<int:context_id>/', views.free_context_modify, name='free_context_modify'),
    path ('free/context/delete/<int:context_id>/', views.free_context_delete, name='free_context_delete'),
    path ('free/context/comment/modify/<int:comment_id>/', views.free_comment_modify, name='free_comment_modify'),
    path ('free/context/comment/delete/<int:comment_id>/', views.free_comment_delete, name='free_comment_delete'),
    path ('trade/', views.trade_index, name='trade_index'),
    path ('trade/<int:context_id>/', views.trade_detail, name='trade_detail'),
    path ('trade/comment/create/<int:context_id>/', views.trade_comment_create, name='trade_comment_create'),
    path ('trade/context/create/', views.trade_context_create, name = 'trade_context_create'),
    path ('trade/context/modify/<int:context_id>/', views.trade_context_modify, name='trade_context_modify'),
    path ('trade/context/delete/<int:context_id>/', views.trade_context_delete, name='trade_context_delete'),
    path ('trade/context/comment/modify/<int:comment_id>/', views.trade_comment_modify, name='trade_comment_modify'),
    path ('trade/context/comment/delete/<int:comment_id>/', views.trade_comment_delete, name='trade_comment_delete'),
    path ('copurchase/', views.copurchase_index, name='copurchase_index'),
    path ('copurchase/<int:context_id>/', views.copurchase_detail, name='copurchase_detail'),
    path ('copurchase/comment/create/<int:context_id>/', views.copurchase_comment_create, name='copurchase_comment_create'),
    path ('copurchase/context/create/', views.copurchase_context_create, name = 'copurchase_context_create'),
    path ('copurchase/context/modify/<int:context_id>/', views.copurchase_context_modify, name='copurchase_context_modify'),
    path ('copurchase/context/delete/<int:context_id>/', views.copurchase_context_delete, name='copurchase_context_delete'),
    path ('copurchase/context/comment/modify/<int:comment_id>/', views.copurchase_comment_modify, name='copurchase_comment_modify'),
    path ('copurchase/context/comment/delete/<int:comment_id>/', views.copurchase_comment_delete, name='copurchase_comment_delete'),
]

my_dorms/config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dorms/', include('dorms.urls')),
    path('common/', include('common.urls')),
    path('washing_machine/', include('washing_machine.urls')),
    re_path(r'^webpush/', include('webpush.urls')),
    path('conversations/',include('conversations.urls')),

]

my_dorms/dorms/urls.py
from django.urls import path
from . import views

app_name = 'dorms'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('<int:context_id>/', views.detail, name='detail'),
    path ('comment/create/<int:context_id>/', views.comment_create, name='comment_create'),
    path ('context/create/', views.context_create, name = 'context_create'),
    path ('context/modify/<int:context_id>/', views.context_modify, name='context_modify'),
    path ('context/delete/<int:context_id>/', views.context_delete, name='context_delete'),
    path ('context/comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path ('context/comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path ('info/', views.info_index, name='info_index'),
    path ('info/<int:context_id>/', views.info_detail, name='info_detail'),
    path ('info/comment/create/<int:context_id>/', views.info_comment_create, name='info_comment_create'),
    path ('info/context/create/', views.info_context_create, name = 'info_context_create'),
    path ('info/context/modify/<int:context_id>/', views.info_context_modify, name='info_context_modify'),
    path ('info/context/delete/<int:context_id>/', views.info_context_delete, name='info_context_delete'),
    path ('info/context/comment/modify/<int:comment_id>/', views.info_comment_modify, name='info_comment_modify'),
    path ('info/context/comment/delete/<int:comment_id>/', views.info_comment_delete, name='info_comment_delete'),
    path ('free/', views.free_index, name='free_index'),
    path ('free/<int:context_id>/', views.free_detail, name='free_detail'),
    path ('free/comment/create/<int:context_id>/', views.free_comment_create, name='free_comment_create'),
    path ('free/context/create/', views.free_context_create, name = 'free_context_create'),
    path ('free/context/modify/<int:context_id>/', views.free_context_modify, name='free_context_modify'),
    path ('free/context/delete/<int:context_id>/', views.free_context_delete, name='free_context_delete'),
    path ('free/context/comment/modify/<int:comment_id>/', views.free_comment_modify, name='free_comment_modify'),
    path ('free/context/comment/delete/<int:comment_id>/', views.free_comment_delete, name='free_comment_delete'),
    path ('trade/', views.trade_index, name='trade_index'),
    path ('trade/<int:context_id>/', views.trade_detail, name='trade_detail'),
    path ('trade/comment/create/<int:context_id>/', views.trade_comment_create, name='trade_comment_create'),
    path ('trade/context/create/', views.trade_context_create, name = 'trade_context_create'),
    path ('trade/context/modify/<int:context_id>/', views.trade_context_modify, name='trade_context_modify'),
    path ('trade/context/delete/<int:context_id>/', views.trade_context_delete, name='trade_context_delete'),
    path ('trade/context/comment/modify/<int:comment_id>/', views.trade_comment_modify, name='trade_comment_modify'),
    path ('trade/context/comment/delete/<int:comment_id>/', views.trade_comment_delete, name='trade_comment_delete'),
    path ('copurchase/', views.copurchase_index, name='copurchase_index'),
    path ('copurchase/<int:context_id>/', views.copurchase_detail, name='copurchase_detail'),
    path ('copurchase/comment/create/<int:context_id>/', views.copurchase_comment_create, name='copurchase_comment_create'),
    path ('copurchase/context/create/', views.copurchase_context_create, name = 'copurchase_context_create'),
    path ('copurchase/context/modify/<int:context_id>/', views.copurchase_context_modify, name='copurchase_context_modify'),
    path ('copurchase/context/delete/<int:context_id>/', views.copurchase_context_delete, name='copurchase_context_delete'),
    path ('copurchase/context/comment/modify/<int:comment_id>/', views.copurchase_comment_modify, name='copurchase_comment_modify'),
    path ('copurchase/context/comment/delete/<int:comment_id>/', views.copurchase_comment_delete, name='copurchase_comment_delete'),
    path ('dormmate/', views.dormmate_index, name='dormmate_index'),
    path ('dormmate/<int:context_id>/', views.dormmate_detail, name='dormmate_detail'),
    path ('dormmate/comment/create/<int:context_id>/', views.dormmate_comment_create, name='dormmate_comment_create'),
    path ('dormmate/context/create/', views.dormmate_context_create, name = 'dormmate_context_create'),
    path ('dormmate/context/modify/<int:context_id>/', views.dormmate_context_modify, name='dormmate_context_modify'),
    path ('dormmate/context/delete/<int:context_id>/', views.dormmate_context_delete, name='dormmate_context_delete'),
    path ('dormmate/context/comment/modify/<int:comment_id>/', views.dormmate_comment_modify, name='dormmate_comment_modify'),
    path ('dormmate/context/comment/delete/<int:comment_id>/', views.dormmate_comment_delete, name='dormmate_comment_delete'),
]

dorms/forms.py
from django import forms
from dorms.models_copy import Context, Comment, Context_info, Comment_info, Context_free, Comment_free, Context_trade, Comment_trade, Comment_copur, Context_copur

class ContextForm (forms.ModelForm) :
    class Meta :
        model = Context
        fields = ['title', 'content']

class CommentForm(forms.ModelForm) :
    class Meta :
        model = Comment
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextInfoForm (forms.ModelForm) :
    class Meta :
        model = Context_info
        fields = ['title', 'content']

class CommentInfoForm(forms.ModelForm) :
    class Meta :
        model = Comment_info
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextFreeForm (forms.ModelForm) :
    class Meta :
        model = Context_free
        fields = ['title', 'content']

class CommentFreeForm(forms.ModelForm) :
    class Meta :
        model = Comment_free
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextTradeForm (forms.ModelForm) :
    class Meta :
        model = Context_trade
        fields = ['title', 'content']

class CommentTradeForm(forms.ModelForm) :
    class Meta :
        model = Comment_trade
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextCopurForm (forms.ModelForm) :
    class Meta :
        model = Context_copur
        fields = ['title', 'content']

class CommentCopurForm(forms.ModelForm) :
    class Meta :
        model = Comment_copur
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

my_dorms/dorms/forms.py
from django import forms
from dorms.models import Context, Comment, Context_info, Comment_info, Context_free, Comment_free, Context_trade, Comment_trade, Comment_copur, Context_copur, Context_dormmate, Comment_dormmate

class ContextForm (forms.ModelForm) :
    class Meta :
        model = Context
        fields = ['title', 'content']

class CommentForm(forms.ModelForm) :
    class Meta :
        model = Comment
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextInfoForm (forms.ModelForm) :
    class Meta :
        model = Context_info
        fields = ['title', 'content']

class CommentInfoForm(forms.ModelForm) :
    class Meta :
        model = Comment_info
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextFreeForm (forms.ModelForm) :
    class Meta :
        model = Context_free
        fields = ['title', 'content']

class CommentFreeForm(forms.ModelForm) :
    class Meta :
        model = Comment_free
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextTradeForm (forms.ModelForm) :
    class Meta :
        model = Context_trade
        fields = ['title', 'content']

class CommentTradeForm(forms.ModelForm) :
    class Meta :
        model = Comment_trade
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class ContextDormmateForm (forms.ModelForm) :
    class Meta :
        model = Context_dormmate
        fields = ['title', 'content', 'isSnoring', 'time_awake_1', 'time_awake_2','time_sleep_1', 'time_sleep_2', 'isSmoking', 'age', 'usingPC','building']    

class CommentDormmateForm(forms.ModelForm) :
    class Meta :
        model = Comment_dormmate
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }
class ContextCopurForm (forms.ModelForm) :
    class Meta :
        model = Context_copur
        fields = ['title', 'content']

class CommentCopurForm(forms.ModelForm) :
    class Meta :
        model = Comment_copur
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

templates/dorms/base.html
{% load static %}
{% load webpush_notifications %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% webpush_header %}
    <title>DORMS</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!--자바스크립트 start-->
{% block script %}
{% endblock %}
<!--자바스크립트 end-->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/dorms/comment_form.html
{% extends 'dorms/base.html' %}
{% block content %}

<nav style="background-color: #1c6758;"class="navbar border-bottom">
    <div id="d-nav" class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
            </li>
        </ul>
        <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
        <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:show' %}">프로필</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
        </ul>
    </div>
</nav>

<div class = "container">
  <h5 class="my-3 border-bottom pb-2">댓글수정</h5>
  <form method="post">
    {% csrf_token %}
    {% include "common/form_errors.html" %}
    <div class="mb-3">
      <label for="content" class="form-label">댓글내용</label>
      <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <div class="position-relative">
      <button style="background-color: #1c6758;"type="submit" class="btn btn-success position-absolute end-0">저장하기</button>
    </div>
  </form>
</div>

{% endblock %}

templates/dorms/context_list.html
{% extends './base.html' %}
{% block content %}

<nav style="background-color: #1c6758;"class="navbar border-bottom">
    <div id="d-nav" class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
            </li>
        </ul>
        <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
        <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:show' %}">프로필</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
        </ul>
    </div>
</nav>

<!-- 네비게이션바 
<nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'dorms:index' %}">공지사항</a>
        <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %} 
            </ul>
    </div>
</nav> -->

<div class="container my-3">
        <table class="table">
            <thead>
            <tr class="table-success" >
                <th style="text-align: center; color: white; background-color: #1c6758;" >#</th>
                <th style="text-align: center; color: white;background-color: #1c6758;" >제목</th>
                
            </tr>
            </thead>
            <tbody>
            {% if context_list %}
            {% for context in context_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a style="color: black; text-decoration-line: none;" href="{% url 'dorms:detail' context.id %}">{{ context.title }}</a>
                </td>
                
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">글이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- <div align="right">
                <a style="background-color: #1c6758;" href= "{% url 'dorms:context_create' %}" class = "fs-10 btn btn-success">게시글 등록</a>
        </div> -->
</div>

<ul class="navbar navbar-light bg-light border-top border-bottom">
    <div class="container-fluid">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item mx-auto">
                <a class="nav-link" href="{% url 'dorms:info_index' %}">정보게시판 </a></li>
            <li class="nav-item mx-auto">
                <a class="nav-link" href="{% url 'dorms:free_index' %}">자유게시판</a></li>
            <li class="nav-item mx-auto">
                <a class="nav-link" href="{% url 'dorms:trade_index' %}">거래게시판</a></li>
            <li class="nav-item mx-auto">
                <a class="nav-link" href="{% url 'dorms:copurchase_index' %}">공동구매게시판</a></li>
        </ul>
    </div>
</ul>


<!--<nav class="navbar navbar-expand-sm navbar-light bg-light border-top border-bottom">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent2"
                aria-controls="navbarSupportedContent2"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent2">
            <ul class="navbar-nav mx-auto">
                    <li class="nav-item mx-auto">
                        <a class="nav-link" href="{% url 'dorms:info_index' %}">정보게시판 </a></li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link" href="{% url 'dorms:free_index' %}">자유게시판</a></li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link" href="{% url 'dorms:trade_index' %}">거래게시판</a></li>
                    <li class="nav-item mx-auto">
                        <a class="nav-link" href="{% url 'dorms:copurchase_index' %}">공동구매게시판</a></li>
            </ul>
        </div>
    </div>
</nav>-->

{% endblock %}

templates/dorms/copur_comment_form.html
{% extends 'dorms/base.html' %}
{% block content %}

<nav style="background-color: #1c6758;"class="navbar border-bottom">
    <div id="d-nav" class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
            </li>
        </ul>
        <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
        <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:show' %}">프로필</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
        </ul>
    </div>
</nav>

<div class = "container">
  <h5 class="my-3 border-bottom pb-2">댓글수정</h5>
  <form method="post">
    {% csrf_token %}
    {% include "common/form_errors.html" %}
    <div class="mb-3">
      <label for="content" class="form-label">댓글내용</label>
      <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <div class="position-relative">
      <button style="background-color: #1c6758;" type="submit" class="btn btn-success position-absolute end-0">저장하기</button>
    </div>
  </form>
</div>

{% endblock %}

templates/dorms/free_context_list.html
{% extends './base.html' %}
{% block content %}

<nav style="background-color: #1c6758;"class="navbar border-bottom">
    <div id="d-nav" class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
            </li>
        </ul>
        <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
        <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:show' %}">프로필</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
        </ul>
    </div>
</nav>

<!-- 네비게이션바 
<nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'dorms:free_index' %}">자유게시판</a>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dorms:index' %}">공지사항</a></li>
        </ul>
    </div>
</nav> -->

<nav class="nav nav-pills bg-light nav-justified border-top border-bottom">
  <a style="color: #1c6758;"
     class="nav-link" href="{% url 'dorms:info_index' %}">정보</a>
  <a style="background-color: #1c6758;"
     class="nav-link active" aria-current="page" href="{% url 'dorms:free_index' %}">자유</a>
  <a style="color: #1c6758;"
     class="nav-link" href="{% url 'dorms:trade_index' %}">거래</a>
  <a style="color: #1c6758;"
     class="nav-link" href="{% url 'dorms:copurchase_index' %}">공동구매</a>
</nav>


<div class="container my-3">
        <table class="table">
            <thead>
            <tr class="table-success">
                <th style="text-align: center; color: white; background-color: #1c6758;" >번호</th>
                <th style="text-align: center; color: white;background-color: #1c6758;" >제목</th>
                <th style="text-align: center; color: white;background-color: #1c6758;" >작성자</th>
            </tr>
            </thead>
            <tbody>
            {% if context_list %}
            {% for context in context_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a style="color: black; text-decoration-line: none;" href="{% url 'dorms:free_detail' context.id %}">{{ context.title }}</a>
                </td>

                <td>{{ context.writer.username }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">글이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <div align="right">
            <a style="background-color: #1c6758;" href= "{% url 'dorms:free_context_create' %}" class = "btn btn-success">게시글 등록</a>
        </div>
 </div>
<!--부트스탧 사용-->
<!--<a href=  "{% url 'dorms:context_create' %}" class = "btn btn-primary">질문등록하기</a>-->


{% endblock %}

templates/dorms/info_context_list.html
{% extends './base.html' %}
{% block content %}

<nav style="background-color: #1c6758;"class="navbar border-bottom">
    <div id="d-nav" class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
            </li>
        </ul>
        <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
        <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:show' %}">프로필</a></li>
                    {% else %}
                        <li class="nav-item">
                            <a style="color: white" class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
        </ul>
    </div>
</nav>

<!-- 네비게이션바 
<nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'dorms:info_index' %}">정보게시판</a>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dorms:index' %}">공지사항</a></li>
            </ul>
    </div>
</nav> -->

<nav class="nav nav-pills bg-light nav-justified border-top border-bottom">
  <a style="background-color: #1c6758;"
     class="nav-link active" aria-current="page" href="{% url 'dorms:info_index' %}">정보</a>
  <a style="color: #1c6758;"
     class="nav-link" href="{% url 'dorms:free_index' %}">자유</a>
  <a style="color: #1c6758;"
     class="nav-link" href="{% url 'dorms:trade_index' %}">거래</a>
  <a style="color: #1c6758;"
     class="nav-link" href="{% url 'dorms:copurchase_index' %}">공동구매</a>
</nav>

<div class="container my-3">
        <table class="table">
            <thead>
            <tr class="table-success">
                <th style="text-align: center; color: white;background-color: #1c6758;" >번호</th>
                <th style="text-align: center; color: white;background-color: #1c6758;" >제목</th>
                <th style="text-align: center; color: white;background-color: #1c6758;" >작성자</th>
            </tr>
            </thead>
            <tbody>
            {% if context_list %}
            {% for context in context_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a style="color: black; text-decoration-line: none;" href="{% url 'dorms:info_detail' context.id %}">{{ context.title }}</a>
                </td>

                <td>{{ context.writer.username }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">글이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <div align="right">
            <a style="background-color: #1c6758;" href= "{% url 'dorms:info_context_create' %}" class = "btn btn-success">게시글 등록</a>
        </div>
 </div>
<!--부트스탧 사용-->
<!--<a href=  "{% url 'dorms:context_create' %}" class = "btn btn-primary">질문등록하기</a>-->


{% endblock %}