common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns=[
    path('main/', views.main, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name = "common/login.html"), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('show/', views.profile_view, name='show'),
    path('show/update/', views.profile_update_view, name='profile_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dorms/', include('dorms.urls')),
    path('common/', include('common.urls')),
    path('washing_machine/', include('washing_machine.urls')),
    re_path(r'^webpush/', include('webpush.urls')),
    path('conversations/',include('conversations.urls')),
]

dorms/urls.py
from django.urls import path
from . import views

app_name = 'dorms'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('<int:context_id>/', views.detail, name='detail'),
    path ('comment/create/<int:context_id>/', views.comment_create, name='comment_create'),
    path ('context/create/', views.context_create, name = 'context_create'),
    path ('context/modify/<int:context_id>/', views.context_modify, name='context_modify'),
    path ('context/delete/<int:context_id>/', views.context_delete, name='context_delete'),
    path ('context/comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path ('context/comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path ('info/', views.info_index, name='info_index'),
    path ('info/<int:context_id>/', views.info_detail, name='info_detail'),
    path ('info/comment/create/<int:context_id>/', views.info_comment_create, name='info_comment_create'),
    path ('info/context/create/', views.info_context_create, name = 'info_context_create'),
    path ('info/context/modify/<int:context_id>/', views.info_context_modify, name='info_context_modify'),
    path ('info/context/delete/<int:context_id>/', views.info_context_delete, name='info_context_delete'),
    path ('info/context/comment/modify/<int:comment_id>/', views.info_comment_modify, name='info_comment_modify'),
    path ('info/context/comment/delete/<int:comment_id>/', views.info_comment_delete, name='info_comment_delete'),
    path ('free/', views.free_index, name='free_index'),
    path ('free/<int:context_id>/', views.free_detail, name='free_detail'),
    path ('free/comment/create/<int:context_id>/', views.free_comment_create, name='free_comment_create'),
    path ('free/context/create/', views.free_context_create, name = 'free_context_create'),
    path ('free/context/modify/<int:context_id>/', views.free_context_modify, name='free_context_modify'),
    path ('free/context/delete/<int:context_id>/', views.free_context_delete, name='free_context_delete'),
    path ('free/context/comment/modify/<int:comment_id>/', views.free_comment_modify, name='free_comment_modify'),
    path ('free/context/comment/delete/<int:comment_id>/', views.free_comment_delete, name='free_comment_delete'),
    path ('trade/', views.trade_index, name='trade_index'),
    path ('trade/<int:context_id>/', views.trade_detail, name='trade_detail'),
    path ('trade/comment/create/<int:context_id>/', views.trade_comment_create, name='trade_comment_create'),
    path ('trade/context/create/', views.trade_context_create, name = 'trade_context_create'),
    path ('trade/context/modify/<int:context_id>/', views.trade_context_modify, name='trade_context_modify'),
    path ('trade/context/delete/<int:context_id>/', views.trade_context_delete, name='trade_context_delete'),
    path ('trade/context/comment/modify/<int:comment_id>/', views.trade_comment_modify, name='trade_comment_modify'),
    path ('trade/context/comment/delete/<int:comment_id>/', views.trade_comment_delete, name='trade_comment_delete'),
    path ('copurchase/', views.copurchase_index, name='copurchase_index'),
    path ('copurchase/<int:context_id>/', views.copurchase_detail, name='copurchase_detail'),
    path ('copurchase/comment/create/<int:context_id>/', views.copurchase_comment_create, name='copurchase_comment_create'),
    path ('copurchase/context/create/', views.copurchase_context_create, name = 'copurchase_context_create'),
    path ('copurchase/context/modify/<int:context_id>/', views.copurchase_context_modify, name='copurchase_context_modify'),
    path ('copurchase/context/delete/<int:context_id>/', views.copurchase_context_delete, name='copurchase_context_delete'),
    path ('copurchase/context/comment/modify/<int:comment_id>/', views.copurchase_comment_modify, name='copurchase_comment_modify'),
    path ('copurchase/context/comment/delete/<int:comment_id>/', views.copurchase_comment_delete, name='copurchase_comment_delete'),
]

my_dorms/config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dorms/', include('dorms.urls')),
    path('common/', include('common.urls')),
    path('washing_machine/', include('washing_machine.urls')),
    re_path(r'^webpush/', include('webpush.urls')),
    path('conversations/',include('conversations.urls')),

]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User (AbstractUser) :
    name = models.CharField(max_length = 200)
    GENDER_CHOICES = (
        ("여학생", "여학생"),
        ("남학생", "남학생"),
    )
    gender = models.CharField(choices = GENDER_CHOICES, max_length = 50)
    BD_CHOICES = (
        ("신관A", "신관A"),
        ("신관B", "신관B"),
        ("인관", "인관"),
        ("의관", "의관"),
        ("예관", "예관"),
        ("지관", "지관"),
        ("C하우스", "C하우스"),
        ("E하우스-본관", "E하우스-별관"),
        ("G하우스", "G하우스"),
        ("I하우스", "I하우스"),
        ("K하우스", "K하우스"),
        ("M하우스-A동", "M하우스-A동"),
        ("M하우스-B동", "M하우스-B동"),
        ("빅토리하우스", "빅토리하우스"),
        ("이완근관", "이완근관"),
        ("크라운빌-A동", "크라운빌-A동"),
        ("크라운빌-C동", "크라운빌-C동"),
    )
    building = models.CharField(choices=BD_CHOICES, max_length=100)
    room_num = models.IntegerField(null=True)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.contrib.auth.forms import UserChangeForm

class UserForm(UserCreationForm):
    class Meta :
        model = User
        fields = ["username", "password1", "password2", "name",
                  "gender","building", "room_num"]

class CustomUserChangeForm (UserChangeForm) :
    password = None
    name = forms.CharField(label='name', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength': '200', }),
        )
    GENDER_CHOICES = (
        ("여학생", "여학생"),
        ("남학생", "남학생"),
    )
    gender = forms.ChoiceField(choices = GENDER_CHOICES, label='gender', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength':'8',} ),
        )
    BD_CHOICES = (
        ("신관A", "신관A"),
        ("신관B", "신관B"),
        ("인관", "인관"),
        ("의관", "의관"),
        ("예관", "예관"),
        ("지관", "지관"),
        ("C하우스", "C하우스"),
        ("E하우스-본관", "E하우스-별관"),
        ("G하우스", "G하우스"),
        ("I하우스", "I하우스"),
        ("K하우스", "K하우스"),
        ("M하우스-A동", "M하우스-A동"),
        ("M하우스-B동", "M하우스-B동"),
        ("빅토리하우스", "빅토리하우스"),
        ("이완근관", "이완근관"),
        ("크라운빌-A동", "크라운빌-A동"),
        ("크라운빌-C동", "크라운빌-C동"),
    )
    building = forms.ChoiceField(choices = BD_CHOICES, label='building', widget = forms.TextInput (
      attrs = {'class': 'form-control', 'maxlength': '100', }),),
    room_num = forms.IntegerField(label='room_num', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'maxlength':'11',}),
    )

    class Meta :
        model = User()
        fields = ['name', 'gender', 'building', 'room_num']

common/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from common.forms import UserForm

# Create your views here.
def main (request) :
    context = {}
    return render (request, 'common/main.html', context)

# def login (request) :
#     return HttpResponse("로그인 페이지입니다.")

# def signup (request) :
#     if request.method == "POST" :
#         form = UserForm(request.POST)
#         if form.is_valid() :
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password) #사용자 인증
#             login(request, user)
#             return redirect('dorms:index')
#         else :
#             form = UserForm()
#     return render (request, 'common/signup.html', {'form':form})

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('dorms:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

my_dorms/common/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import UserForm, CustomUserChangeForm
from .models import User
from dorms.models import Context
from conversations.services.chat_room_service import get_an_chat_room_list, get_chat_room_user, confirm_user_chat_room_join, \
    creat_an_chat_room, creat_an_room_join

# Create your views here.
def main (request) :
    context_list = Context.objects.all()[:5]
    context = {
        'context_list' : context_list
    }
    return render (request, 'common/main.html', context)

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            #이웃한 방 유저 체크하고 메시지 room 생성
            try: 
                neighbor1 = User.objects.get(building=user.building, room_num=user.room_num+1)
                room = creat_an_chat_room()
                room_id = room.id
                creat_an_room_join(user, neighbor1, room)
                
            except User.DoesNotExist:
                neighbor1 = None
            try: 
                neighbor2 = User.objects.get(building=user.building, room_num=user.room_num-1)
                room = creat_an_chat_room()
                room_id = room.id
                creat_an_room_join(user, neighbor2, room)
            except User.DoesNotExist:
                neighbor2 = None

            



            login(request, user)  # 로그인
            return redirect('common:main')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

def profile_view (request) :
    if request.method == 'GET' :
        return render (request, 'common/profile.html')

def profile_update_view(request) :
    if request.method == 'POST' :
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)

        if user_change_form.is_valid() :
            user = user_change_form.save()
            user.save()
            return render (request, 'common/profile.html')

    else :
        user_change_form = CustomUserChangeForm(instance=request.user)

    return render (request, 'common/profile_update.html', {'user_change_form':user_change_form})

templates/common/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
<!--    사용자가 입력한 필드 값에 오류로 값이 누락되었거나 필드의 형식이 일치하지 않는 경우-->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 : 다른 이유 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/common/login.html
{% extends "dorms/base.html" %}
{% block content %}
<nav style="background-color: #1c6758;"class="navbar border-bottom">
  <div id="d-nav" class="container-fluid">
      <ul class="navbar-nav">
          <li class="nav-item">
              <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
          </li>
      </ul>
      <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
      <ul>      </ul>
  </div>
</nav>

<div class="login_box">
  <div><p class="logo_text">RED:orm</p></div>
  <form method="post" action="{% url 'common:login' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="//127.0.0.1:8000/common/main">  <!--    로그인 성공 후 이동되는 URL-->
    <div class="login_grid">
      <input type="text" class="login_input" name="username" id="username" placeholder="ID"
        value="{{ form.username.value|default_if_none:'' }}">
      <input type="password" class="login_input" name="password" id="password" placeholder="PassWord"
        value="{{ form.password.value|default_if_none:'' }}">
      <button type="submit" class="login_button">로그인</button>
    </div>
    <a href="{% url 'common:signup' %}" class="register_link">아직 회원이 아니신가요?</a>
    {% include "common/form_errors.html" %}
  </form>
</div>
{% endblock %}

templates/common/main.html
{% extends "dorms/base.html" %}
{% block content %}
<div class="up_bar">
  <div></div>
  <div><p class="logo_text">RED:orm</p></div>
  <div>
    {% if user.is_authenticated %}
    <a href="{% url 'common:show' %}" class="login_link">프로필</a>
    {%else%}
    <a href="{% url 'common:login' %}" class="login_link">로그인</a>
    {%endif%}
  </div>
</div>

<div class="content_box" style="margin-top: 20px;">
  <div class="main_notice_title">
    공지사항
    <a href="//127.0.0.1:8000/dorms/" class="main_additional_link">더보기 ></a>
  </div>
  <div class="main_notice_list">
    {% if context_list %}
    {% for context in context_list %}
    <a href="{% url 'dorms:detail' context.id %}" class="main_notice_element">{{context.title}}</a>
    <p>{{context.writer.username}}</p>
    {% endfor %}
    {% endif %}

  </div>
</div>

<div class="content_grid">
  <div class="board_box" onclick="location.href='{% url 'dorms:info_index' %}'">
  </div>

  <div class="laundry_box" onclick="location.href='//127.0.0.1:8000/washing_machine'">
  </div>
  {% if user.is_authenticated %}
  <a href="//127.0.0.1:8000/massenger/chatting_list" class="float_button"></a>
  {%endif%}
</div>
{% endblock %}

templates/common/profile.html
{% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- 네비게이션바 -->
<nav style="background-color: #1c6758;"class="navbar border-bottom">
    <div id="d-nav" class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
            </li>
        </ul>
        <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
        <ul>      </ul>
    </div>
</nav>

  <div class="login_box" style="height: fit-content;">
      <div class="logo_text" style="margin-bottom: 30px;">
        마이페이지
      </div>
      <table style="margin: auto; margin-bottom: 30px; text-align: center;">
          <tr>
              <td class="register_field" style="margin: 0px;"><b>이름</b></td>
              {% comment %} <td>김명륜</td> {% endcomment %}
              <td>{{ user.name }}</td>
          </tr>
          <tr>
            <td class="register_field" style="margin: 0px;"><b>성별</b></td>
            {% comment %} <td>5학기</td> {% endcomment %}
            <td>{{ user.gender }}</td>
          </tr>
          <tr>
            <td class="register_field" style="margin: 0px;"><b>기숙사 건물</b></td>
            {% comment %} <td>신관A</td> {% endcomment %}
            <td>{{ user.building }}</td>
          </tr>
          <tr>
            <td class="register_field" style="margin: 0px;"><b>방 호수</b></td>
            {% comment %} <td>102</td> {% endcomment %}
              <td>{{ user.room_num }}</td>
          </tr>
      </table>
      <a href="{% url 'common:profile_update' %}" class="profile_update_link">프로필 수정</a>
      <a href="{% url 'common:logout' %}" class="logout_link">로그아웃</a>
  </div>

templates/common/profile_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <nav style="background-color: #1c6758;"class="navbar border-bottom">
        <div id="d-nav" class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
                </li>
            </ul>
            <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
            <ul>      </ul>
        </div>
    </nav>

    <div class="register_box" style="height: fit-content;">
        <form method="post" action="{% url 'common:profile_update' %}">
            {% csrf_token %}
            {{form.as_p}}
            <div class="logo_text" style="margin-bottom: 30px;">
                회원정보 수정
            </div>

            <div class="mb-3" style="margin-top:50px">
                <div>{{user.username}} 님</div>
            </div>

            <div class="mb-3" style="margin-top: 20px;">
                <label for="name" class="register_field">
                    <b>이름</b>
                </label>
                <br>
                <input type="text" class="register_input_field" name="name" id="name"
                    value="{{ form.nickname.value|default_if_none:'' }}">
            </div>

            <div style="margin-top: 10px;">
                <b class="register_field">성별</b> <br>
                <select class="register_input_field" name="gender" id="gender">
                  <option value="">***성별***</option>
                  <option value="남학생">남학생</option>
                  <option value="여학생">여학생</option>
                </select>
            </div>

            <div style="margin-top: 10px;">
                <b class="register_field">기숙사 건물</b> <br>
                <select class="register_input_field" name="building" id="building">
                  <option value="">***기숙사 건물***</option>
                  <option value="인관">인관</option>
                  <option value="의관">의관</option>
                  <option value="예관">예관</option>
                  <option value="지관">지관</option>
                  <option value="신관A">신관A</option>
                  <option value="신관B">신관B</option>
                </select>
            </div>

            <div style="margin-top: 10px;">
                <b class="register_field">방 호수</b> <br>
                <input type="number" class="register_input_field" name="room_num" id="room_num" placeholder="Room Number (Ex. 123)"
                  value="room_num">
            </div>

            <div class="button" style="text-align:center; margin-top:20px">
                <button type="submit" class="register_button" style="width: 80%;">
                    수정하기
                </button>
            </div>
        </form>
    </div>

</body>
</html>

templates/common/signup.html
{% extends "dorms/base.html" %}
{% block content %}
<nav style="background-color: #1c6758;"class="navbar border-bottom">
  <div id="d-nav" class="container-fluid">
      <ul class="navbar-nav">
          <li class="nav-item">
              <div style="color: white" class="nav-link" onClick="history.go(-1)">뒤로가기</div>
          </li>
      </ul>
      <a style="color: white" class="navbar-brand" href="{% url 'common:main' %}">RED:orm</a>
      <ul>      </ul>
  </div>
</nav>

<div class = "register_box">
  <div><p class="logo_text">RED:orm</p></div>
  <form method="post" action="{% url 'common:signup' %}" style="margin-top: 20px;">
    {% csrf_token %}
    {% include "common/form_errors.html" %}
    <div>
      <b class="register_field">ID</b> <br>
      <input type="text" class="register_input_field" name="username" id="username" placeholder="ID" 
        value="{{ form.username.value|default_if_none:'' }}">
    </div>

    <div style="margin-top: 10px;">
      <b class="register_field">비밀번호</b> <br>
      <input type="password" class="register_input_field" name="password1" id="password1" placeholder="PW" 
      value="{{ form.password1.value|default_if_none:'' }}">
    </div>

    <div>
      <input type="password"class="register_input_field" name="password2" id="password2" placeholder="PW Repeat"
      value="{{ form.password2.value|default_if_none:'' }}">
    </div>

    <div style="margin-top: 10px;">
      <b class="register_field">닉네임</b> <br>
      <input type="text" class="register_input_field" name="name" id="name" placeholder="User Name"
        value="{{ form.username.value|default_if_none:'' }}">
    </div>

    <div style="margin-top: 10px;">
      <b class="register_field">기숙사 건물</b> <br>
      <select class="register_input_field" name="building" id="building">
        <option value="">***기숙사 건물***</option>
        <option value="인관">인관</option>
        <option value="의관">의관</option>
        <option value="예관">예관</option>
        <option value="지관">지관</option>
        <option value="신관A">신관A</option>
        <option value="신관B">신관B</option>
      </select>
    </div>

    <div style="margin-top: 10px;">
      <b class="register_field">성별</b> <br>
      <select class="register_input_field" name="gender" id="gender">
        <option value="">***성별***</option>
        <option value="남학생">남학생</option>
        <option value="여학생">여학생</option>
      </select>
    </div>

    <div style="margin-top: 10px;">
      <b class="register_field">방 호수</b> <br>
      <input type="number" class="register_input_field" name="room_num" id="room_num" placeholder="Room Number (Ex. 123)"
        value="room_num">
    </div>

    <button type="submit" class="register_button">회원가입</button>
  </form>

</div>

{% endblock %}